
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD DIV INT LP MUL RP SUBE : E ADD FE : E SUB FE : FF : F MUL GF : F DIV GF : GG : LP E RPG : INT'
    
_lr_action_items = {'LP':([0,4,6,7,8,9,],[4,4,4,4,4,4,]),'INT':([0,4,6,7,8,9,],[5,5,5,5,5,5,]),'$end':([1,2,3,5,11,12,13,14,15,],[0,-3,-6,-8,-1,-2,-4,-5,-7,]),'ADD':([1,2,3,5,10,11,12,13,14,15,],[6,-3,-6,-8,6,-1,-2,-4,-5,-7,]),'SUB':([1,2,3,5,10,11,12,13,14,15,],[7,-3,-6,-8,7,-1,-2,-4,-5,-7,]),'RP':([2,3,5,10,11,12,13,14,15,],[-3,-6,-8,15,-1,-2,-4,-5,-7,]),'MUL':([2,3,5,11,12,13,14,15,],[8,-6,-8,8,8,-4,-5,-7,]),'DIV':([2,3,5,11,12,13,14,15,],[9,-6,-8,9,9,-4,-5,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'E':([0,4,],[1,10,]),'F':([0,4,6,7,],[2,2,11,12,]),'G':([0,4,6,7,8,9,],[3,3,3,3,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> E","S'",1,None,None,None),
  ('E -> E ADD F','E',3,'p_e_plus','main.py',29),
  ('E -> E SUB F','E',3,'p_e_minus','main.py',34),
  ('E -> F','E',1,'p_e_r','main.py',39),
  ('F -> F MUL G','F',3,'p_f_mul','main.py',44),
  ('F -> F DIV G','F',3,'p_f_div','main.py',49),
  ('F -> G','F',1,'p_f_r','main.py',54),
  ('G -> LP E RP','G',3,'p_g_paren','main.py',59),
  ('G -> INT','G',1,'p_g_num','main.py',64),
]
